CREATE TABLE IF NOT EXISTS paper_accounts (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    initial_cash DECIMAL(18,2) NOT NULL,
    cash DECIMAL(18,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    config_json LONGTEXT NOT NULL,
    config_version INT NOT NULL DEFAULT 1,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_paper_accounts_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS paper_runs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    run_type VARCHAR(20) NOT NULL,
    trade_date DATE NOT NULL,
    data_date DATE DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    message TEXT,
    code_version VARCHAR(100) DEFAULT NULL,
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at DATETIME DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_paper_runs_account_time (account_id, started_at),
    CONSTRAINT fk_paper_runs_account FOREIGN KEY (account_id) REFERENCES paper_accounts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS paper_config_versions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    config_json LONGTEXT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_paper_config_version (account_id, version_no),
    CONSTRAINT fk_paper_config_account FOREIGN KEY (account_id) REFERENCES paper_accounts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS paper_signals (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    run_id BIGINT NOT NULL,
    signal_date DATE NOT NULL,
    signal_time DATETIME NOT NULL,
    data_date DATE NOT NULL,
    stock_code VARCHAR(10) NOT NULL,
    stock_name VARCHAR(100) DEFAULT NULL,
    industry VARCHAR(100) DEFAULT NULL,
    strategy_code VARCHAR(80) NOT NULL,
    strategy_name VARCHAR(100) NOT NULL,
    score DECIMAL(10,3) DEFAULT NULL,
    reason TEXT,
    quote_price DECIMAL(18,4) DEFAULT NULL,
    quote_time DATETIME DEFAULT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'CANDIDATE',
    status_reason VARCHAR(255) DEFAULT NULL,
    config_version INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_paper_signal (account_id, signal_date, stock_code, strategy_code),
    KEY idx_paper_signals_date (account_id, signal_date),
    CONSTRAINT fk_paper_signals_account FOREIGN KEY (account_id) REFERENCES paper_accounts (id),
    CONSTRAINT fk_paper_signals_run FOREIGN KEY (run_id) REFERENCES paper_runs (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS paper_positions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    signal_id BIGINT NOT NULL,
    stock_code VARCHAR(10) NOT NULL,
    stock_name VARCHAR(100) DEFAULT NULL,
    strategy_code VARCHAR(80) NOT NULL,
    strategy_name VARCHAR(100) NOT NULL,
    config_version INT NOT NULL,
    quantity INT NOT NULL,
    entry_time DATETIME NOT NULL,
    entry_price DECIMAL(18,4) NOT NULL,
    entry_fee DECIMAL(18,2) NOT NULL DEFAULT 0,
    take_profit_price DECIMAL(18,4) NOT NULL,
    stop_loss_price DECIMAL(18,4) NOT NULL,
    max_holding_days INT NOT NULL,
    commission_rate DECIMAL(12,8) NOT NULL,
    min_commission DECIMAL(18,2) NOT NULL,
    sell_tax_rate DECIMAL(12,8) NOT NULL,
    slippage_bps DECIMAL(10,4) NOT NULL,
    current_price DECIMAL(18,4) NOT NULL,
    current_quote_time DATETIME DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    exit_time DATETIME DEFAULT NULL,
    exit_price DECIMAL(18,4) DEFAULT NULL,
    exit_fee DECIMAL(18,2) DEFAULT NULL,
    exit_tax DECIMAL(18,2) DEFAULT NULL,
    realized_pnl DECIMAL(18,2) DEFAULT NULL,
    exit_reason VARCHAR(100) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_paper_positions_open (account_id, status),
    KEY idx_paper_positions_stock (account_id, stock_code),
    CONSTRAINT fk_paper_positions_account FOREIGN KEY (account_id) REFERENCES paper_accounts (id),
    CONSTRAINT fk_paper_positions_signal FOREIGN KEY (signal_id) REFERENCES paper_signals (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS paper_cash_ledger (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    position_id BIGINT DEFAULT NULL,
    event_time DATETIME NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    amount DECIMAL(18,2) NOT NULL,
    balance_after DECIMAL(18,2) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_paper_cash_ledger_time (account_id, event_time),
    CONSTRAINT fk_paper_cash_account FOREIGN KEY (account_id) REFERENCES paper_accounts (id),
    CONSTRAINT fk_paper_cash_position FOREIGN KEY (position_id) REFERENCES paper_positions (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS paper_nav_daily (
    id BIGINT NOT NULL AUTO_INCREMENT,
    account_id BIGINT NOT NULL,
    trade_date DATE NOT NULL,
    cash DECIMAL(18,2) NOT NULL,
    market_value DECIMAL(18,2) NOT NULL,
    total_assets DECIMAL(18,2) NOT NULL,
    realized_pnl DECIMAL(18,2) NOT NULL,
    unrealized_pnl DECIMAL(18,2) NOT NULL,
    total_fees DECIMAL(18,2) NOT NULL,
    daily_pnl DECIMAL(18,2) NOT NULL,
    daily_return_pct DECIMAL(12,6) NOT NULL,
    cumulative_return_pct DECIMAL(12,6) NOT NULL,
    drawdown_pct DECIMAL(12,6) NOT NULL,
    positions_count INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_paper_nav_daily (account_id, trade_date),
    CONSTRAINT fk_paper_nav_account FOREIGN KEY (account_id) REFERENCES paper_accounts (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
